test-job:
  stage: my-test
  script:
    - |
     echo "This is confidential $MY_NAME"
     echo "This is confidential $MY_AGE"
     echo "This is confidential $ENV"
     python python-scripts/first.py
     
